CORE-config_reader.py-34-get: config returning api.request.timeout: 20
CORE-response.py-26-__init__: API Response body : 
	('{\n'
 '  "userId": 1,\n'
 '  "id": 1,\n'
 '  "title": "sunt aut facere repellat provident occaecati excepturi optio '
 'reprehenderit",\n'
 '  "body": "quia et suscipit\\nsuscipit recusandae consequuntur expedita et '
 'cum\\nreprehenderit molestiae ut ut quas totam\\nnostrum rerum est autem '
 'sunt rem eveniet architecto"\n'
 '}')
CORE-response.py-27-__init__: API Response headers : 
	("{'Date': 'Thu, 25 Apr 2019 11:56:09 GMT', 'Content-Type': 'application/json; "
 "charset=utf-8', 'Content-Length': '292', 'Connection': 'keep-alive', "
 "'Set-Cookie': '__cfduid=dc65366ff206e0b650f6ff9f6765e7c4b1556193369; "
 'expires=Fri, 24-Apr-20 11:56:09 GMT; path=/; domain=.typicode.com; '
 "HttpOnly', 'X-Powered-By': 'Express', 'Vary': 'Origin, Accept-Encoding', "
 "'Access-Control-Allow-Credentials': 'true', 'Cache-Control': 'public, "
 "max-age=14400', 'Pragma': 'no-cache', 'Expires': 'Thu, 25 Apr 2019 15:56:09 "
 "GMT', 'X-Content-Type-Options': 'nosniff', 'Etag': "
 '\'W/"124-yiKdLzqO5gfBrJFrcdJ8Yq0LGnU"\', \'Via\': \'1.1 vegur\', '
 "'CF-Cache-Status': 'HIT', 'Accept-Ranges': 'bytes', 'Expect-CT': "
 "'max-age=604800, "
 'report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"\', '
 "'Server': 'cloudflare', 'CF-RAY': '4cd021cf9f07a89f-CDG'}")
CORE-response.py-28-__init__: API Response cookies : 
	('<RequestsCookieJar[<Cookie '
 '__cfduid=dc65366ff206e0b650f6ff9f6765e7c4b1556193369 for .typicode.com/>]>')
CORE-response.py-29-__init__: API Response status code : 
	'200'
CORE-delayed_assertions.py-35-_log_failure: 1 : Assertion error occured in file test_api.py at line no 20, in test test_get_posts
                assertion.expect(response.body.userId == 3)

            
        
CORE-delayed_assertions.py-43-_report_failures: 
Asserting all expectations: 
	In test test_get_posts at line no 21

CORE-delayed_assertions.py-44-_report_failures: Failed Expectations:1

CORE-delayed_assertions.py-58-_report_failures: 
Asserting all expectations: 
	In test test_get_posts at line no 21

Failed Expectations:1

1 : Assertion error occured in file test_api.py at line no 20, in test test_get_posts
                assertion.expect(response.body.userId == 3)

            
        
